services:
  _defaults:
    autowire: true
    autoconfigure: true

  Akondas\ActuatorBundle\Controller\:
    resource: '../../../src/Controller'
    tags: [ 'controller.service_arguments' ]

  Akondas\ActuatorBundle\Service\Info\InfoCollector: ~
