parameters:
  akondas.health.disk_space.default_threshold: 52428800
  akondas.health.disk_space.threshold: '%env(default:akondas.health.disk_space.default_threshold:int:HEALTH_INDICATOR_DISK_SPACE_THRESHOLD)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Akondas\ActuatorBundle\Controller\:
    resource: '../../../src/Controller'
    tags: [ 'controller.service_arguments' ]

  Akondas\ActuatorBundle\Service\Info\InfoCollector: ~

  Akondas\ActuatorBundle\Service\Health\DiskSpaceHealthIndicator: 
    tags: ['akondas.health_indicator']
    arguments:
      - '%kernel.project_dir%'
      - '%akondas.health.disk_space.threshold%'

  Akondas\ActuatorBundle\Service\Health\HealthIndicatorStack:
    arguments:
      - !tagged_iterator akondas.health_indicator

